// OUR OWN TYPES
#include "common/error.hpp"

#define VMA_IMPLEMENTATION

W3D_DISABLE_WARNINGS();

// IN THIS FILE WE'LL BE DECLARING METHODS DECLARED INSIDE THIS HEADER FILE
#include <vk_mem_alloc.h>

W3D_ENABLE_WARNINGS();
